version: '3'
services:

  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_final_project
    ports:
      - "5000:5000"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - .:/final_project
